const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);
  console.log("Account balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH");

  const VotingSystem = await ethers.getContractFactory("VotingSystem");
  const voting = await VotingSystem.deploy();
  await voting.waitForDeployment();
  const address = await voting.getAddress();

  console.log("\n✅ VotingSystem deployed at:", address);

  // Save address + ABI to frontend
  const frontendDir = path.join(__dirname, "../frontend/src/utils");
  if (!fs.existsSync(frontendDir)) fs.mkdirSync(frontendDir, { recursive: true });

  // Get ABI from artifacts
  const artifact = JSON.parse(
    fs.readFileSync(
      path.join(__dirname, "../artifacts/contracts/VotingSystem.sol/VotingSystem.json"),
      "utf8"
    )
  );

  fs.writeFileSync(
    path.join(frontendDir, "contract.js"),
    `// Auto-generated by deploy.js — do not edit manually
export const CONTRACT_ADDRESS = "${address}";
export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`
  );

  console.log("📁 Contract address + ABI saved to frontend/src/utils/contract.js");
  console.log("\nNext steps:");
  console.log("  cd frontend && npm install && npm start");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
